### PR TITLE
Fixes for macOS build

### PR DESCRIPTION
**Pull request by e40**
Thanks @damienstuart for help with this.  It builds and works on macOS 14.3 with up-to-date Homebrew and Xcode.

### CODE REVIEW

**Comment by damienstuart** [comment]
Hi.  I recommend you keep the AC_PREREQ value at 2.62.  Most other distributions (including the latest Fedora and Ubuntu) have autoconf 2.71 or lower.  We want to avoid forcing a newer version of Autoconf that is not available via the normal distributions.  

Since AC_PREREQ specifies the minimum required version, please resubmit the pull request with it set at its current value.

Thanks,

-Damien

**Comment by e40** [comment]
> Hi. I recommend you keep the AC_PREREQ value at 2.62. Most other distributions (including the latest Fedora and Ubuntu) have autoconf 2.71 or lower. We want to avoid forcing a newer version of Autoconf that is not available via the normal distributions.
> 
> Since AC_PREREQ specifies the minimum required version, please resubmit the pull request with it set at its current value.
> 
> Thanks,
> 
> -Damien

Done.  Let me know if there's anything else you'd like changed.

Thanks for the help.

**Comment by e40** [comment]
@damienstuart should I change the version number or is that only done after a release?

**Comment by damienstuart** [comment]
No need to change the version. That is typically done just prior to a release.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mrash** [comment]
Thanks, with these latest updates seems like we should go ahead and publish
the next version.

Mike

**Pull request merged**
