### PR TITLE
Needs review -- refactors the client's nat validation

### PR DESCRIPTION
**Pull request by oneru**
This adds is_valid_hostname() to common/fko_util, and then uses that function in both the server and the client to validate nat strings.

Updates a failing test with the new error message, resulting in a passing test.

Adds a basic c-unit test for is_valid_hostname().

Removes the "NAT bogus IP validation" test, as the bogus IP tested is technically a valid hostname.

### CODE REVIEW

**Comment by mrash** [comment]
Thanks, I'll take a look by tomorrow night.

**Comment by oneru** [comment]
@mrash rather than remove that test altogether, we should just rewrite it to be almost an IP address, but also not a valid hostname.  Maybe "192,168.1.1".  Any other thoughts on this patchset?

**Comment by mrash** [comment]
Sounds like a good strategy for the test. I'm working intermittently today on your other test suite changes as well.

**Comment by oneru** [comment]
This afternoon I'll amend this PR to reflect that strategy, then.  I'm also toying with the idea of including the c-unit tests as part of the perl test quite.  The advantage would be that they run under valgrind, and could count towards our coverage statistics.  Thoughts?

**Comment by mrash** [comment]
Sure, on c-unit tests and code coverage, I think there are a couple of things to check. First, that the c-unit code itself is included in coverage results, and that functions exercised by it are also included. I suspect both of these to be the case, but we need to be sure. Also, it would be handy to have it integrated with the test suite as you say because it would be easy to get code coverage results for just the c-unit tests. This would help us enhance the c-unit tests to cover areas of the code that it currently misses, and it probably isn't easy to know which lines we're currently missing without such coverage results.

**Comment by oneru** [comment]
Made that update.  The changed test might still be failing, but at least now it's a problem in fwknop, not the test suite.

**Comment by oneru** [comment]
@mrash I'm thinking we need to also pass the string length into is_valid_hostname() and is_valid_ipv4().  When we have a string that is (ip-address),(port) or something similar, the validator functions expect a null terminator instead of the comma to separate the two strings.  

Let me know what you think, I might close this PR, finish and push the is_valid_*() changes and associated CUnit tests, and then we can look at the rest of it one chunk at a time.  This PR is getting to be large and unwieldy.

**Comment by mrash** [comment]
Sounds good to me to go ahead and push this one. We can look at the rest piecemeal as you suggest.

**Comment by oneru** [comment]
I've re-worked and pushed a few of these changes, will work through the rest and open a simpler PR later tonight.

**Pull request closed without merging**
