### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by oneru**
This is the first of a series of cleanups I would like to make.  In hmac.c, the code logic jumped through too many unneeded functions.  This simplifies the hmac functions.  They all still pass the CUnit tests, so should be working correctly.

### CODE REVIEW

**Comment by oneru** [comment]
Once again I've probably pushed too many items into one pull request, but these should be all fairly straightforward.

**Comment by mrash** [comment]
One comment on this set of changes - all of the return values from the new malloc() calls in the hmac_* functions need to be checked against NULL. If malloc() has returned NULL, then failure should be returned to fko_set_spa_hmac() and it should in turn return FKO_ERROR_MEMORY_ALLOCATION. So, the hmac_* function prototypes would need to be updated to not return void. Also, using calloc() would be slightly better to harden against the slight possibility of mishandling of the placement of a NULL byte - libfko generally uses calloc().

Btw, I can make a section on cipherdyne.org for the Doxygen stuff (which is really cool).

**Comment by oneru** [comment]
@mrash Understood, I'll make the changes you described.  Should be fairly simple.  

As soon as doxygen began generating useful output, I began making heavy use of it as a reference while working on other bits of fwknop.  It's already been a very handy tool to have.  I look forward to finishing that documentation for the whole project.

**Comment by oneru** [comment]
@mrash Also, perhaps we should add a doxygen page documenting the "best practice" standards for Fwknop, things like calloc over malloc, etc.

**Comment by mrash** [comment]
That's a great idea. The fwknop code gets influenced by a lot of different tools that I use to heighten security. There are probably some general guiding principles that come out of this. One thing I haven't done yet is run the CLANG static analyzer on the SHA3 stuff. If you are interested in taking a look at this, just do:

$ scan-build ./configure --prefix=/usr --sysconfdir=/etc
$ scan-build make

$ scan-view /tmp/scan-build-2016-01-11-2

Then connect to:

http://127.0.0.1:8181/

Or just run the whole thing under 'script' and you can see the warnings in the console output. The CLANG static analyzer is pretty good, but it does generate false positives from time to time.

**Comment by mrash** [comment]
Btw, just say the word when you think the doxygen stuff should go on cipherdyne.org. Or, I can link to your site if you prefer.

**Pull request merged**
